### PR TITLE
fix layout path for config

### PR DESCRIPTION
**Pull request by Fujiyura**
Thanks. I like this theme and I use it.
But... I was troubled with the its initial settings.

The "README" says,
```
## Configuration
following settings are for theme.
 ```
but  some layout files reference not "[HexoDirectory]/theme/simple-japanese/config.yml" but "[hexoDirectory]/config.yml"
So I encounter an error when my first set this theme according to the sample in "README.md".

I wondered if I should fix README file. But I decided to fix layout files because I think it should be placed design settings such as custom_css under the theme directory.

### CODE REVIEW

**Comment by mitsuruog** [comment]
@Fujiyura Thanks for the pull request! I have a couple of questions. 

1. Which version of Hexo are you using?

2. Could you show me your `_config.yml`?
Since I am new to the `theme` configuration part. I want to see how you are configuring this part.

**Comment by Fujiyura** [comment]
@mitsuruog  Thank you for the reply. I'll answer your questions.

1.
> Which version of Hexo are you using?

The Hexo's version I'm using is "5.1.1".
"package.json" says as follows:
```
hexo": {
    "version": "5.1.1"
  },
  "dependencies": {
    "hexo": "^5.0.0",
...
  }
```

2.
> Could you show me your _config.yml?

I'll attach the file that I'm using it in my test project.
The one on project root is this:
[_config.yml.txt](https://github.com/mitsuruog/hexo-theme-simple-japanese/files/5202929/_config.yml.txt)
The one on theme project (simple-japanese) root is this:
[_config.yml.txt](https://github.com/mitsuruog/hexo-theme-simple-japanese/files/5203034/_config.yml.txt)

**Comment by mitsuruog** [comment]
Thanks for sharing! 
Unfortunately, this theme does not support theme configuration for now. 
You need to put all theme config values to `_config.yml` where the root of your project.

Please see this real-world example.
- https://github.com/mitsuruog/blog.mitsuruog.info/blob/master/_config.yml#L77-L100

**Comment by mitsuruog** [comment]
@Fujiyura 
The entire theme configuration needs to be reviewed, and it will bring some breaking changes, so I create a 1.0 branch and merge it in for now.
Until then, please try the workaround above.

**Comment by Fujiyura** [comment]
Oh. thanks.

>  You need to put all theme config values to _config.yml where the root of your project.

OK. I understund how this theme's configuration written,
But...by the way, In "profile.ejs" referenced "theme.contact.url" and "theme.contact.icon".
follows;
https://github.com/mitsuruog/hexo-theme-simple-japanese/blob/master/layout/_widget/profile.ejs#L12-L13

If I put all theme config values to _config.yml where the root of my project, Does it work ?

**Pull request merged**
